# Generated by Django 3.0.2 on 2020-01-25 09:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, null=True, verbose_name='Title')),
                ('start', models.DateTimeField(default=datetime.datetime(2020, 1, 25, 10, 15, 1, 964750), null=True, verbose_name='Start date')),
                ('end', models.DateTimeField(default=datetime.datetime(2020, 1, 25, 10, 15, 1, 964750), null=True, verbose_name='Start date')),
            ],
        ),
    ]
