# Generated by Django 3.0.2 on 2020-01-25 09:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_auto_20200125_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='end',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 25, 10, 49, 5, 20595), null=True, verbose_name='Start date'),
        ),
        migrations.AlterField(
            model_name='post',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 25, 10, 49, 5, 20595), null=True, verbose_name='Start date'),
        ),
    ]
