# Generated by Django 3.0.2 on 2020-01-26 14:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_auto_20200125_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='event_id',
            field=models.CharField(max_length=1024, null=True, verbose_name='Event id'),
        ),
        migrations.AlterField(
            model_name='post',
            name='end',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 26, 15, 36, 19, 208318), null=True, verbose_name='Start date'),
        ),
        migrations.AlterField(
            model_name='post',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 26, 15, 36, 19, 208318), null=True, verbose_name='Start date'),
        ),
    ]
