# Generated by Django 3.0.2 on 2020-01-26 16:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_auto_20200126_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='end',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 26, 17, 0, 39, 96554), null=True, verbose_name='Start date'),
        ),
        migrations.AlterField(
            model_name='post',
            name='event_id',
            field=models.CharField(default='N/A', max_length=1024, null=True, verbose_name='Event id'),
        ),
        migrations.AlterField(
            model_name='post',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 26, 17, 0, 39, 96554), null=True, verbose_name='Start date'),
        ),
    ]
