# Generated by Django 3.0.2 on 2020-01-27 18:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_auto_20200127_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='end',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 27, 19, 2, 14, 373793), null=True, verbose_name='Start date'),
        ),
        migrations.AlterField(
            model_name='post',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 27, 19, 2, 14, 373793), null=True, verbose_name='Start date'),
        ),
    ]
