# Generated by Django 3.0.2 on 2020-01-27 18:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0007_auto_20200127_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='end',
            field=models.DateTimeField(default=datetime.datetime.now, null=True, verbose_name='Start date'),
        ),
        migrations.AlterField(
            model_name='post',
            name='start',
            field=models.DateTimeField(default=datetime.datetime.now, null=True, verbose_name='Start date'),
        ),
    ]
